### ISSUE TITLE
Wait Page Loaded

### ISSUE THREAD

**Issue by ghost** [ThomasHansson/Appium-cross-platform-example#2]
Hi,

Very nice example.
I have try to follow you code to be my baseline.
I have testing your code on my hybrid app.
How to wait for page load/element showing?

Below is my log when try to check my button label.
On the first the page is not loaded fully (maybe). And after loaded the test result is error.

```
// verify the label
introductionPage.assertSkipLabel("LEWATI");

Feb 07, 2019 12:03:56 PM io.appium.java_client.remote.AppiumCommandExecutor$1 lambda$0
INFO: Detected dialect: W3C
Expected:LEWATI
Actual:

java.lang.AssertionError: expected [] but found [LEWATI]
Expected :
Actual   :LEWATI
```

**Comment by ThomasHansson** [comment]
Hard to say from that log snippet. But note that if you are running in a hybrid app with a webview you need to change the context of the test to that webview. See http://appium.io/docs/en/writing-running-appium/web/hybrid/
