### ISSUE TITLE
Null Pointer exception

### ISSUE THREAD

**Issue by divyangsolanki** [ThomasHansson/Appium-cross-platform-example#3]
searchPage.search("Sara");

On this line it is giving null pointer exception. And when i am trying to implement like you have implemented every time it is giving null pointer exception.

**Comment by ThomasHansson** [comment]
Could it be that you have set the executionOS flag to something different than OS.ANDROID, OS.IOS, OS.ANDROID_BROWSERSTACK or OS.IOS_BROWSERSTACK in the AppiumController class. SearchPage is initialized in the BaseTestClass but only for those executionOS parameters.
